On branch feature/all-pipeline
Your branch is up to date with 'origin/feature/all-pipeline'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   .pre-commit-config.yaml

no changes added to commit (use "git add" and/or "git commit -a")
