name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  python-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - run: |
          if [ -f tests/test.py ]; then python tests/test.py; else echo "No tests found."; fi
  node-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: |
          if [ -f package-lock.json ]; then npm ci; elif [ -f package.json ]; then npm install; fi
      - run: |
          if [ -f package.json ]; then npm test || echo "No tests found."; fi
  gradle-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - run: |
          if [ -f gradlew ]; then ./gradlew build; elif [ -f build.gradle.kts ]; then gradle build; else echo "No Gradle build file found."; fi
