name: Deploy DivineNode via AWS Copilot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Copilot Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout DivineNode repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy using Copilot
        uses: fuji97/aws-ecs-copilot-deploy@v1.1
        with:
          app: divine-node
          env: production
          svc: core
